### ISSUE TITLE
Non-equispaced Lagrange elements on simplices

### ISSUE THREAD

**Issue by pbrubeck** [firedrakeproject/fiat#45]
If we want to implement simplicial Lagrange elements with the recursive nodes from https://epubs.siam.org/doi/pdf/10.1137/20M1321802, should we implement them as a new class or could they be the extension of the 1D elements (`GaussLegendre` and `GaussLobattoLegendre`) that we already have?

**Comment by dham** [comment]
If the elements reduce to GL and GLL in 1D then please extend those elements. This will make integration in Firedrake more seamless

**Comment by pbrubeck** [comment]
Fixed by #46
