### ISSUE TITLE
Arnold-Winther element is incorrect

### ISSUE THREAD

**Issue by mscroggs** [firedrakeproject/fiat#85]
In the [Arnold-Winther paper](https://doi.org/10.1007/s002110100348), it says that the lowest degree AW element has 24 DOFs:

![image](https://github.com/user-attachments/assets/a8d0c434-1c56-4ccf-b0f6-dd2e34f845f7)

However the degree 3 AW element in FIAT has 30 DOFs:

![image](https://github.com/user-attachments/assets/13d16f5d-e5b8-4aae-80c0-5b3f94312b4c)

**Comment by wence-** [comment]
This is handled by the reference to physical transformation in finat: https://github.com/FInAT/FInAT/blob/e72e533860420f16959084d1007e3e5512b56da6/finat/aw.py#L155

The rationale for this is explained Rob's 2018 paper on tranformation theory (the Bell element is similar)

**Comment by mscroggs** [comment]
Thanks, that's very helpful.

Closing this as I now agree that FIAT's AW is correct
