### ISSUE TITLE
FIAT reluctant to create high-order quadrature rules

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/fiat#9]
Because of [this sanity check](https://github.com/firedrakeproject/fiat/blob/master/FIAT/quadrature_schemes.py#L104). However, high order quadrature degrees are completely legitimate when solving for high-order discretisations. @wence-: what should we do?

**Comment by wence-** [comment]
This was a sanity check I put in because people kept on creating non-polynomial integrands that had ludicrous estimated degrees and so the quadrature was massive overkill.  I agree that these schemes are entirely legit for high-degree elements.  Shall we just remove it?

**Comment by wence-** [comment]
Perhaps we could add a warning in the form compiler if the estimated degree is more than a factor 10 (?) larger than the degree of the test/trial spaces?

**Comment by dorugeber** [comment]
I approve

**Comment by miklos1** [comment]
Thanks, this sounds good.

**Comment by miklos1** [comment]
Fixed in upstream master. firedrakeproject/tsfc#128 is adding a better alternative.
